# Generated by Django 5.1.1 on 2024-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraccount',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
