# Generated by Django 5.1.1 on 2024-09-30 13:50
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('RPS', '0002_alter_playeraccount_email'),
    ]
    operations = [
        migrations.AlterField(
            model_name='playeraccount',
            name='userName',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]