# Generated by Django 5.1 on 2024-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0004_player_userid_alter_player_losses_alter_player_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1ID', models.IntegerField()),
                ('p2ID', models.IntegerField()),
                ('p1Choice', models.CharField(blank=True, max_length=8)),
                ('p2Choice', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
