# Generated by Django 5.1.1 on 2024-10-01 12:50
import django.db.models.deletion
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('RPS', '0007_alter_gameroom_p2id'),
    ]
    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='gameID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RPS.game'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='p1ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerOne', to='RPS.player'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='p2ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerTwo', to='RPS.player'),
        ),
    ]