# Generated by Django 5.1 on 2024-10-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0008_gameroom_isprivate_alter_gameroom_gameid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1Finalize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='p1Seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='p2Finalize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='p2Seen',
            field=models.BooleanField(default=False),
        ),
    ]
