# Generated by Django 5.1 on 2024-10-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPS', '0009_game_p1finalize_game_p1seen_game_p2finalize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='p1ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerOneGame', to='RPS.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='p2ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerTwoGame', to='RPS.player'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='p1ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerOneRoom', to='RPS.player'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='p2ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerTwoRoom', to='RPS.player'),
        ),
    ]
